- batch: 128
  config: generated_configs/twin/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: twin
- batch: 128
  config: generated_configs/twin/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: twin
- batch: 128
  config: generated_configs/preFer/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: preFer
- batch: 128
  config: generated_configs/preFer/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: preFer
- batch: 128
  config: generated_configs/partnership-after-2020/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: partnership-after-2020
- batch: 128
  config: generated_configs/partnership-after-2020/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: partnership-after-2020
- batch: 128
  config: generated_configs/INPA2023TABV1/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: INPA2023TABV1
- batch: 128
  config: generated_configs/INPA2023TABV1/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: INPA2023TABV1
- batch: 128
  config: generated_configs/INPA2022TABV1/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: INPA2022TABV1
- batch: 128
  config: generated_configs/INPA2022TABV1/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: INPA2022TABV1
- batch: 128
  config: generated_configs/divorce-after-2020/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: divorce-after-2020
- batch: 128
  config: generated_configs/divorce-after-2020/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: divorce-after-2020
- batch: 128
  config: generated_configs/divorce-after-2020/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: divorce-after-2020
- batch: 128
  config: generated_configs/divorce-after-2020/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: divorce-after-2020
- batch: 128
  config: generated_configs/liss_filtered/medium-random/lr1e-03_bs128.json
  lr: 0.001
  model: medium-random
  task: liss_filtered
- batch: 128
  config: generated_configs/liss_filtered/ccall-random/lr1e-03_bs128.json
  lr: 0.001
  model: ccall-random
  task: liss_filtered
